name: Data Schema Code Convention

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  code_convention_check:
    name: Check Code Convention for Data Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Перевірка SQL-файлів за допомогою sqlite3
      - name: Validate SQL Files
        run: |
          for file in $(find . -name "*.sql"); do
            echo "Validating $file"
            sqlite3 :memory: ".read $file" || (echo "SQL validation failed for $file" && exit 1)
          done

      # Перевірка JSON-файлів за допомогою jq
      - name: Validate JSON Files
        run: |
          for file in $(find . -name "*.json"); do
            echo "Validating $file"
            jq . "$file" > /dev/null || (echo "Invalid JSON in $file" && exit 1)
          done
