name: Data Schema Code Convention

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  code_convention_check:
    name: Check Code Convention for Data Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Validate SQL files using sqlite3
      - name: Validate SQL Files
        run: |
          for file in $(find . -name "*.sql"); do
            echo "Validating $file"
            sqlite3 :memory: ".read $file" || (echo "SQL validation failed for $file" && exit 1)
          done

   
