name: Validate SQL Code Style

on:
  push:
    paths:
      - '*.sql'
  pull_request:
    paths:
      - '*.sql'

jobs:
  lint-sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install sql-lint
        run: npm install -g sql-lint

      - name: Lint SQL files
        run: sql-lint DataSchema.sql
